name: Makefile CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "*.md"
      - "LICENSE"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "*.md"
      - "LICENSE"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make setup

    - name: Build with PyInstaller
      run: make build
